=== ricardoleal24/PRI2020/TPC2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (pagetitle,header,workteam,abstract,deliverables,date) >
<!ELEMENT pagetitle (#PCDATA) >
<!ELEMENT header (keyname,title,subtitle?,begindate,enddate,supervisor) >
<!ELEMENT keyname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT begindate (#PCDATA)>
<!ELEMENT enddate (#PCDATA)>
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor 
                link CDATA #REQUIRED >


<!ELEMENT workteam (member)+ >
<!ELEMENT member (#PCDATA) >
<!ATTLIST member 
            link CDATA #REQUIRED>


<!ELEMENT abstract (par+) >
<!ELEMENT par (#PCDATA|b|i)* >
<!ELEMENT b (#PCDATA|i)* >
<!ELEMENT i (#PCDATA|b)* >

<!ELEMENT deliverables (item)+>
<!ELEMENT item (#PCDATA) >
<!ATTLIST  item
           link CDATA #REQUIRED>
<!ELEMENT date (#PCDATA) >

=== ricardoleal24/PRI2020/TPC2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/home/ricardoleal24/Storage/20-21/PLC/PRI/TPC2/pr.dtd">
<pr>
    <pagetitle>Project Record</pagetitle>
    <header>
        <keyname>PRI2019-A75411-TPC2</keyname>
        <title>Especificação de DTD's/Queries XPath</title>
        <subtitle>TPC2</subtitle>
        <begindate>19 Outubro 2020</begindate>
        <enddate>26 Outubro 2020</enddate>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <member link="a75411@alunos.uminho.pt">Ricardo Guerra Leal</member>
    </workteam>
    <abstract>
        <par>Este Project Record foi gerada com recurso a um ficheiro anotado
             em <b>DTD</b> (<i>Document type definition</i>), onde se define a 
             estrutura,elementos e atributos de um ficheiro<b>XML</b>.</par>
        <par>Com recurso ao <b>XPath</b> realizaram-se Queries sobre o ficheiro
             XML <i>arqueossítios</i>.</par>
    </abstract>
    <deliverables>
        <item link="pr.dtd">pr.dtd</item>
        <item link="pr.xml">pr.xml</item>
        <item link="arq.xml">arq.xml</item>
        <item link="queriesXPath.txt">queriesXPath.txt</item>
    </deliverables>
    <date>25 Outubro 2020</date>
</pr>

=== ricardoleal24/PRI2020/TPC3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/home/ricardoleal24/Storage/20-21/PLC/PRI/TPC2/pr.dtd">
<pr>
    <pagetitle>Project Record</pagetitle>
    <header>
        <keyname>PRI2019-A75411-TPC3</keyname>
        <title>Stylesheets XSLT</title>
        <subtitle>TPC3</subtitle>
        <begindate>26 Outubro 2020</begindate>
        <enddate>2 Novembro 2020</enddate>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <member link="a75411@alunos.uminho.pt">Ricardo Guerra Leal</member>
    </workteam>
    <abstract>
        <par>Neste trabalho utilizou-se a linguagem <b>XSL</b> <i>(eXtensible Stylesheet Language)</i>
            para escrever stylesheets de transformação de ficheiros <b>XSL</b>, para ficheiros <b>HTML</b>.</par>
    </abstract>
    <deliverables>
        <item link="arq.dtd">arq.dtd</item>
        <item link="arq.xsl">arq.xsl</item>
        <item link="index.html">index.html</item>
    </deliverables>
    <date>1 novembro 2020</date>
</pr>
